# nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
    "@nestjs/core@*":
        peerDependenciesMeta:
            "@nestjs/platform-express":
                optional: true

    "@nestjs/common@*":
        peerDependenciesMeta:
            "class-validator":
                optional: true
            "class-transformer":
                optional: true